language: python
cache: pip
python:
    - "2.7"
    - "3.5"
#command to install depedancies
install:
    - pip install -r requirements.txt
    - pip install .
    - pip install tox-travis
    - pip install coverage
    - pip install codecov
# command to run tests
script:
    - tox
after_success:
    - codecov