language: python
cache: pip
python:
    - "2.7"
    - "3.5"
#command to install depedancies
install:
    - pip install --upgrade -r requirements.txt
    - pip install --upgrade .
    - pip install --upgrade tox-travis
    - pip install -r requirements.txt
# command to run tests
script: tox
after_success: coveralls